name: dnext_chatbot_3
description: "DNext ChatBot Application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.2
  flutter: 3.24.2

dependencies:
  flutter:
    sdk: flutter
  http:
  equatable:
  get:
  faker: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true